// !!! This is a file automatically generated by hipify!!!
/*
primeoutlist.cuh

Host function for the primeOutList class, which creates host and device arrays
of primes for output (primeList is internal)

(c) 2016
Curtis Seizert <cseizert@gmail.com>

 */
 #include <hip/hip_runtime.h>
 #include <hip/hip_runtime.h>
 #include <stdint.h>

 #include "../HIPSieve/host.hpp"
 // #include "CUDASieve/cudasieve.hpp"
 #include "HIPSieve/global.cuh"
